### ISSUE TITLE
FOSSBilling support

### ISSUE THREAD

**Issue by xinomilo** [dondominio/boxbilling-plugin#1]
hey,

since boxbilling seems abandoned and all efforts seem to point to [FOSSBilling](https://fossbilling.org/) nowadays, is it possible to make this plugin compatible with fossbilling? 

tbh, tried to use this plugin, but gives 500 error and breaks fossbilling completely (manually altering mysql to workaround issue....). 

can help test it if you like. 

thanks,
d.

**Comment by insxa** [comment]
Hello, i need this too, can you integrate ?

**Comment by mateusan** [comment]
Plugin FossBilling

https://github.com/dondominio/fossbilling-plugin

@xinomilo @insxa @treborin
